name: bioio-sldy
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - dask
  - fsspec
  - xarray
  - pyyaml
  - tifffile
  - matplotlib
  - jupyter
  - ipykernel
  - pip
  - pip:
    - bioio-base>=0.3.0
    - -e .
